### ISSUE TITLE
[Suggestion] Customizable Knockback

### ISSUE THREAD

**Issue by AllOutJay** [Flooflez/BetterVanillaSnowballs#3]
Hi there,

Thank you for updating the mod again! 

I was wondering if there was any opportunity for making snowballs (ideally eggs and fishing bobbers too) have customizable knockback like a mod similar to the one you have? [Snowball and Egg Knockback](https://modrinth.com/mod/snowball-and-egg-knockback)

**Comment by Flooflez** [comment]
Done!
Available for 1.21 and 1.21.1 on [Modrinth](https://modrinth.com/mod/better-snowball-fights/version/1.21.1-1.1.1) and Curseforge soon.
