### ISSUE TITLE
[1.21.1-1.1.1] Crash - Snowball Entity onEntityHit mixin assumes that the snowball always has an owner

### ISSUE THREAD

**Issue by TigerWalts** [Flooflez/BetterVanillaSnowballs#4]
Snowball projectiles may be emitted by blocks that themselves have no owner to inherit or may be spawned by a mod without an owner.

Crash Log - https://mclo.gs/NlAzYX1

Crashes on line 47 due to `owner` being `Null`:

https://github.com/Flooflez/BetterVanillaSnowballs/blob/11bbad221ad3b17bc4720dfc3f1ac09714f83d65/src/main/java/net/better/snowball/fights/mixin/SnowballEntityMixin.java#L27-L56

**Comment by Flooflez** [comment]
awesome bug report thanks :)
working on it now

**Comment by Flooflez** [comment]
fixed, new version going up soon for 1.21.1, .3 and .4
